RunAction "00-MainAction", oneIteration
'RunAction "01-HomeAction", oneIteration
'RunAction "02-CarBrand-MAZDA", oneIteration
'RunAction "02-CarBrand-Landrover", oneIteration
'RunAction "02-CarBrand-Chevrolet", oneIteration
'RunAction "03-Trad-Step1", oneIteration
'RunAction "04-CarModel-MAZDA", oneIteration
'RunAction "04-CarModel-Chevrolet", oneIteration
'RunAction "04-CarModel-Landrover", oneIteration
'RunAction "05-CarColor-MAZDA", oneIteration
'RunAction "05-CarColor-Landrover", oneIteration
'RunAction "05-CarColor-Chevrolet", oneIteration
'RunAction "06-License-huA", oneIteration
'RunAction "06-License-huC", oneIteration
'RunAction "06-License-waiPaiSH", oneIteration
'RunAction "07-PayModel-AllPay", oneIteration
'RunAction "07-PayModel-Loan", oneIteration
'RunAction "07-PayModel-Pay&Swap", oneIteration
'RunAction "07-PayModel-Loan&Swap", oneIteration
'RunAction "08-PurchaseTime-m3Month", oneIteration
'RunAction "08-PurchaseTime-i3Month", oneIteration
'RunAction "08-PurchaseTime-i1Month", oneIteration
'RunAction "08-PurchaseTime-i2Week", oneIteration
'RunAction "09-Area", oneIteration
'RunAction "10-Trad-Step9", oneIteration
'RunAction "11-RegisterLogin", oneIteration
'RunAction "06-License-waiPaiAH", oneIteration
'RunAction "12-AdminLogin", oneIteration
'RunAction "13-VerifyCode", oneIteration
'RunAction "14-OderList", oneIteration